export const ADD_POKEMON_DETAIL_START = "ADD_POKEMON_DETAIL_START";
export const ADD_POKEMON_DETAIL_SUCCESS = "ADD_POKEMON_DETAIL_SUCCESS";
export const ADD_POKEMON_DETAIL_ERROR = "ADD_POKEMON_DETAIL_ERROR";
